version: '2'
services:
  nginx:
    build: ./docker/nginx
    image: rugs-nginx:0.0.1
    container_name: rugs_nginx
    ports:
      - "80:80"
    environment:
      AUTH_USER: "${AUTH_USER}"
      AUTH_PASS: "${AUTH_PASS}" 
  endpoint-http:
    build: ./docker/rugs
    image: rugs-app:0.0.1
    container_name: rugs_endpoint_http
<<<<<<< HEAD
    command: ./endpoint_http.py
=======
    command: /app/endpoint_http.py
>>>>>>> 9bbae51d2b1446c37d434931696571cb91540c2a
    tty: true
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
      - "5570:5570"
  worker-logger:
    build: ./docker/rugs
    image: rugs-app:0.0.1
    container_name: rugs_worker_logger
<<<<<<< HEAD
    command: ./worker.py
=======
    command: /app/worker_logger.py
>>>>>>> 9bbae51d2b1446c37d434931696571cb91540c2a
    tty: true
    volumes:
      - ./app:/app
    environment:
      MODULE: "logger"
      TOPIC: "logger"
   